### ISSUE TITLE
Sono nato storto

### ISSUE THREAD

**Issue by klamerja** [klamerja/MTSS_TEST#1]
**Describe the bug**
Ho un problema nella testa, funziona a metà

**To Reproduce**
Parla al Meria

**Expected behavior**
Parte mentalmente

**Screenshots**
Per la privacy, non forniamo immagini

**Desktop (please complete the following information):**
- MacOs Sonoma

**Additional context**
Sus

**Comment by klamerja** [comment]
# SONO RIMASTO STORTO

**Comment by Mircodj** [comment]
**### _

> MA DIVERSI DA LOROOO

_**
